"""Added certificate db models

Revision ID: 0f726cb54c71
Revises: 25b817d8be70
Create Date: 2020-08-28 23:56:33.340289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f726cb54c71'
down_revision = '25b817d8be70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('root_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('pubkey', sa.Text(), nullable=True),
    sa.Column('privkey', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_certificate_name'), 'root_certificate', ['name'], unique=False)
    op.create_table('intermediate_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('pubkey', sa.Text(), nullable=True),
    sa.Column('privkey', sa.Text(), nullable=True),
    sa.Column('root', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['root'], ['root_certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intermediate_certificate_name'), 'intermediate_certificate', ['name'], unique=False)
    op.create_table('certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('pubkey', sa.Text(), nullable=True),
    sa.Column('intermediate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intermediate'], ['intermediate_certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_name'), 'certificate', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificate_name'), table_name='certificate')
    op.drop_table('certificate')
    op.drop_index(op.f('ix_intermediate_certificate_name'), table_name='intermediate_certificate')
    op.drop_table('intermediate_certificate')
    op.drop_index(op.f('ix_root_certificate_name'), table_name='root_certificate')
    op.drop_table('root_certificate')
    # ### end Alembic commands ###
