"""Added default fields to the user model

Revision ID: c7a8b36094a2
Revises: e3fc91247e39
Create Date: 2020-09-10 14:45:25.523812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a8b36094a2'
down_revision = 'e3fc91247e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('user', sa.Column('locality', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('org_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('ou_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state')
    op.drop_column('user', 'ou_name')
    op.drop_column('user', 'org_name')
    op.drop_column('user', 'locality')
    op.drop_column('user', 'country')
    # ### end Alembic commands ###
