"""Add private key to certificate model

Revision ID: e3fc91247e39
Revises: 0f726cb54c71
Create Date: 2020-08-29 19:46:44.736268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fc91247e39'
down_revision = '0f726cb54c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('privkey', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate', 'privkey')
    # ### end Alembic commands ###
